void getHeight();
void getRightDis(int TRIG,int ECHO);
void getLeftDis();
void forward(int speed,int time);
void yaw();
void throttleUp();
void throttleDown();
void getFrontDisRight();
void getFrontDisLeft();
bool isStuckFront();
void sonarSensorInit();
void getAngle();
void calibAccelGyro();
void calibMotor();
void calcAccelYPR();
void calcFilteredYPR();
void printValue();